FileVersion = 1

[Project]
Name = "minimp3-beef"
DefaultNamespace = "minimp3"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\minimp3.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\minimp3.lib"]